FROM node:22-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y clang libc++-dev libc++abi-dev

COPY package.json yarn.lock ./
COPY worker/package.json worker/package.json
COPY packages/cost/package.json packages/cost/package.json
COPY packages/llm-mapper/package.json packages/llm-mapper/package.json
COPY packages/common/package.json packages/common/package.json
COPY packages/secrets/package.json packages/secrets/package.json
COPY packages/prompts/package.json packages/prompts/package.json
COPY packages/filters/package.json packages/filters/package.json

RUN yarn install --frozen-lockfile

COPY worker worker
COPY packages/cost packages/cost
COPY packages/llm-mapper packages/llm-mapper
COPY packages/common packages/common
COPY packages/secrets packages/secrets
COPY packages/prompts packages/prompts
COPY packages/filters packages/filters
WORKDIR /app/worker
RUN find /app/worker -name ".env.*" -exec rm {} \;

RUN rm -rf ./.wrangler

CMD env > .dev.vars && echo "n" | npx wrangler dev --local --enable-containers=false --var WORKER_TYPE:${WORKER_TYPE} --ip 0.0.0.0 --port ${WORKER_PORT}
